/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import ENTRANCE from "./script/ENTRANCE"
import Joystick from "./script/Joystick"
import onload_s from "./script/onload_s"
import CameraBehavior from "./CameraBehavior"
import CharacterController from "./CharacterController"
import ConstEvent from "./script/ConstEvent"
import menu from "./script/menu"
import GameUI from "./script/GameUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="test/menu.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/ENTRANCE.ts",ENTRANCE);
        reg("script/Joystick.ts",Joystick);
        reg("script/onload_s.ts",onload_s);
        reg("CameraBehavior.ts",CameraBehavior);
        reg("CharacterController.ts",CharacterController);
        reg("script/ConstEvent.ts",ConstEvent);
        reg("script/menu.ts",menu);
        reg("script/GameUI.ts",GameUI);
    }
}
GameConfig.init();